### ISSUE TITLE
Clean the frontend from any authentication mechanism

### ISSUE THREAD

**Issue by pdonorio** [pdonorio/restangulask#29] opened 2016-06-10 12:38 UTC
It is not needed anymore, now that we found that JWT can carry all the informations needed.

So we should:
- [x] Share the secret inside the `commons` dir code created in the issue #22 
- [x] take care of [this comment](https://github.com/EUDAT-B2STAGE/http-api-base/issues/17#issuecomment-225120186) inside the issue EUDAT-B2STAGE/http-api-base#17

**Comment by pdonorio** [comment] 2016-06-10 12:39
@mdantonio if you find other things to remove in the python frontend code, put that here as a reminder.

**Comment by mdantonio** [comment] 2016-06-10 13:09
For now i don't find other relevant blocks of dead code. 
However with the extension of unit tests to frontend, all dead code will be easly discovered

**Comment by pdonorio** [comment] 2016-06-12 12:14
> However with the extension of unit tests to frontend, all dead code will be easly discovered

Uhm... but should we use any unit test for the frontend side, now that with this issue we are going to remove the only separated endpoints?

**Comment by mdantonio** [comment] 2016-06-13 06:20
Some features should be tested, just to be sure in production.
For example the creation of blueprint.js

We could consider it as a very low priority task, but nevertheless a task to do

**Comment by pdonorio** [comment] 2016-06-15 10:27
Whenever you have time, go for it!

**Comment by mdantonio** [comment] 2016-07-26 05:37
This issue (clean frontend from authentication and blocks of dead code) is completed.
The issue is still open due to a derived task (make tests on frontend).
I tried to make some tests but it is not trivial and also considering the very very low priority i think we can close this issue.
After completed tests on the web interface (#19) probabily we will be able to add some tests to frontend (or at least reconsider this task)

**Closed as completed by mdantonio** 2016-07-26 05:37 UTC
